# Generated by Django 2.1.2 on 2018-12-26 02:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='question_desc',
            field=models.CharField(max_length=800, null=True),
        ),
    ]
