# Generated by Django 2.1.8 on 2019-05-22 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bbs', '0002_question_question_desc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='choice',
            name='choice_text',
            field=models.TextField(max_length=2000),
        ),
    ]
