# Generated by Django 2.1.2 on 2018-12-26 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='region',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
